apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: practice
  labels:
    app: simple-crud-app
spec:
  selector:
    app: simple-crud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80